version: '3.2'
services:
  case-study:
    build: .
    image: case-study:local
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_HOST=db
      - POSTGRES_DB=test
      - PGUSER=test
      - PGDATABASE=test
    volumes:
      - .:/app
    ports:
      - 5432:5432
